import requests
from twilio.rest import Client
# For pythonanywhere free account.
import os
from twilio.http.http_client import TwilioHttpClient

# Your Account Sid and Auth Token from twilio.com/console
# and set the environment variables. See http://twil.io/secure
account_sid = 'TWILIO_ACCOUNT_SID'
auth_token = 'TWILIO_AUTH_TOKEN'
client = Client(account_sid, auth_token)

parameters = {
    "lat": -4.441931,
    "lon": 15.266293,
    "exclude": "current,minutely,daily",
    "appid": "a5132cf41ea41adf227a72ff78e9f41e"
}

response = requests.get(f"https://api.openweathermap.org/data/2.5/onecall", params=parameters)
hourlydata = response.json()["hourly"]

will_rain = False

for i in range(12):
    if hourlydata[i]["weather"][0]["id"] < 700:
        will_rain =True

if will_rain == True:
    # For pythonanywhere free account.
    #proxy_client = TwilioHttpClient()
    #proxy_client.session.proxies = {'https': os.environ['https_proxy']}
    #client = Client(account_sid, auth_token, http_client=proxy_client)
    message = client.messages \
        .create(
        body="Its going to rain today, please carry umbrella",
        from_='+15017122661', # enter from number generated by twilio api
        to='+15558675310'  # enter receivers number
    )

    print(message.sid)
# More examples at : https://www.twilio.com/docs/sms/quickstart/python
# https://help.pythonanywhere.com/pages/TwilioBehindTheProxy/